// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var b = "Hello world";

console.log(10);

console.log(b);

var a = 10;

exports.a = a;
exports.b = b;
/*  Not a pure module */
